### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by AlexYenkalov** [walt-id/waltid-storagekit#6]
Hello,

We are looking to explore your implementation of Confidential Storage to potentially integrate it into our product. But so far JS/TS makes the core of our stack. 
Fo that reason, we wonder if you already work or have a plan to release TS library for "Storage Kit Client (Client)" and "Service wrapper (Service)" anytime soon?

Looking forward to your reply and trying out this kit.

Regards,
Alex

**Comment by waltkb** [comment]
One of our long-term goals is to move towards Kotlin Multiplatform, as this would allow us to also have the target platforms JS and native. However, right now the libraries we depend on are from the JVM ecosystem.
